#ifndef _BDB_ESP_Pins_H
#define _BDB_ESP_Pins_H

#include "hal/gpio_types.h"

typedef enum {
    BDB_ESP_DAC_VOUT0_PIN = GPIO_NUM_1,
    BDB_ESP_DAC_VOUT1_PIN = GPIO_NUM_2,
    BDB_ESP_FPGA_RESET_PIN = GPIO_NUM_4,
    BDB_ESP_FPGA_CDONE_PIN = GPIO_NUM_5,
    BDB_ESP_GP_I2C_SDA = GPIO_NUM_6,
    BDB_ESP_GP_I2C_SCL = GPIO_NUM_7,
    BDB_ESP_GP_SPI_SIO3 = GPIO_NUM_9,
    BDB_ESP_PSRAM_CS = GPIO_NUM_10,
    BDB_ESP_GP_SPI_MOSI = GPIO_NUM_11,
    BDB_ESP_GP_SPI_SCK = GPIO_NUM_12,
    BDB_ESP_GP_SPI_MISO = GPIO_NUM_13,
    BDB_ESP_GP_SPI_SIO2 = GPIO_NUM_14,
    BDB_ESP_DAC_CS = GPIO_NUM_16,
    BDB_ESP_STM_CS = GPIO_NUM_17,
    BDB_ESP_STM_BOOT0 = GPIO_NUM_18,
    BDB_ESP_LED_PIN = GPIO_NUM_21,
    BDB_ESP_FPGA_TX = GPIO_NUM_33,
    BDB_ESP_FPGA_CS = GPIO_NUM_34,
    BDB_ESP_STM_NJTRST = GPIO_NUM_35,
    BDB_ESP_TPICLK = GPIO_NUM_36,
    BDB_ESP_ATTINY_RESET = GPIO_NUM_37,
    BDB_ESP_STM_RESET = GPIO_NUM_38,
    BDB_ESP_STM_JTDI = GPIO_NUM_39,
    BDB_ESP_STM_JTDO = GPIO_NUM_40,
    BDB_ESP_STM_JTCK = GPIO_NUM_41,
    BDB_ESP_STM_JTMS = GPIO_NUM_42,
    BDB_ESP_STM_RX = GPIO_NUM_43,
    BDB_ESP_STM_TX = GPIO_NUM_44
} bdb_esp_pin_t;

#endif // _BDB_ESP_Pins_H