#ifndef _BDB_ATTINY_DEF_H
#define _BDB_ATTINY_DEF_H

// Memory MAP
#define ATTINY_MEMORY_IOSPACE_ADDR 0x0000
#define ATTINY_MEMORY_IOSPACE_SIZE 0x0040
#define ATTINY_MEMORY_SRAM_ADDR 0x0040
#define ATTINY_MEMORY_SRAM_ADDR 0x80
#define ATTINY_MEMORY_NVMLOCKBITS_ADDR 0x3F00
#define ATTINY_MEMORY_NVMLOCKBITS_ADDR 0x0002
#define ATTINY_MEMORY_CONFIGURATIONBITS_ADDR 0x3F40
#define ATTINY_MEMORY_CONFIGURATIONBITS_SIZE 0x0002
#define ATTINY_MEMORY_CALIBRATIONBITS_ADDR 0x3F80
#define ATTINY_MEMORY_CALIBRATIONBITS_SIZE 0x0002
#define ATTINY_MEMORY_DEVICEIDBITS_ADDR 0x3FC0
#define ATTINY_MEMORY_DEVICEIDBITS_SIZE 0x0004
#define ATTINY_MEMORY_FLASH_ADDR 0x4000
#define ATTINY_MEMORY_FLASH_SIZE 0x0800

// Timings
#define t_TOUT_US 256 * 1000 // Time-out after reset
#define t_RST_US 1           // Minimum pulse width on RESET Pin

#endif // _BDB_ATTINY_DEF_H